# Generated by Django 5.1.7 on 2025-03-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_id', models.CharField(max_length=100, unique=True)),
                ('gis_data', models.JSONField()),
                ('soil_type', models.CharField(max_length=100)),
                ('weather', models.CharField(max_length=100)),
                ('npk_levels', models.JSONField()),
                ('moisture', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
        ),
    ]
